global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - send_resolved: true
    channel: '#prometheus'
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ }}
      {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
        {{" "}}
    title_link: '{{ template "slack.default.titlelink" . }}'
    text: >-
      {{ range .Alerts -}}
       *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
       *Decription:* {{ .Annotations.description }}
       *Details:*
        {{ range .Labels.SortedPairs }} - *{{ .Name }}:* `{{ .Value }}`
        {{ end }}
      {{ end }}